source "https://rubygems.org"

gem "activerecord", "~> 5.2"
gem "sinatra-activerecord"
gem "rake"

gem "require_all"
gem "sqlite3"
gem "pry"
gem 'activerecord-reset-pk-sequence'
gem 'colorize'


# The gems I added.
gem 'faker'
gem 'tty-prompt'
